services:
  - type: web
    name: nurt-reseler-bot
    env: python
    buildCommand: pip install --prefer-binary -r requirements.txt
    startCommand: python bot.py
    envVars:
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: ADMIN_TELEGRAM_IDS
        sync: false
      - key: DATABASE_URL
        sync: false
      - key: WEBHOOK_URL
        sync: false
      - key: WEBHOOK_PATH
        value: /webhook
      - key: PORT
        value: 10000
